<?php

declare(strict_types=1);

namespace Tests\Oracle;

use PHPUnit\Framework\TestCase;
use UDA\Database;
use UDA\Exception\ConfigException;
use UDA\Exception\QueryException;

abstract class OracleTestCase extends TestCase
{
    protected const CONNECTION_NAME = 'oracle';

    private static ?Database $db = null;

    private static ?string $ownedConfigPath = null;

    private static ?string $skipReason = null;

    private static bool $numbersTableInitialized = false;

    private static bool $employeesTableInitialized = false;

    private static bool $usersTableInitialized = false;

    private bool $errorHandlerActive = false;

    protected function setUp(): void
    {
        parent::setUp();

        set_error_handler([$this, 'suppressIdentifierWarnings'], E_WARNING);
        $this->errorHandlerActive = true;

        if (!extension_loaded('pdo_oci')) {
            self::markTestSkipped('pdo_oci extension is required for Oracle integration.');
        }

        if (self::$db === null && self::$skipReason === null) {
            self::initializeDatabase();
        }

        if (self::$skipReason !== null) {
            self::markTestSkipped(self::$skipReason);
        }
    }

    public static function tearDownAfterClass(): void
    {
        if (self::$ownedConfigPath !== null && is_file(self::$ownedConfigPath)) {
            unlink(self::$ownedConfigPath);
            self::$ownedConfigPath = null;
        }

        self::$db = null;
        self::$skipReason = null;
        self::$numbersTableInitialized = false;
        self::$employeesTableInitialized = false;
        self::$usersTableInitialized = false;
    }

    protected function tearDown(): void
    {
        if ($this->errorHandlerActive) {
            restore_error_handler();
            $this->errorHandlerActive = false;
        }

        parent::tearDown();
    }

    protected function db(): Database
    {
        \assert(self::$db !== null, 'Oracle database connection must be initialized.');

        return self::$db;
    }

    protected function resetUsersTable(): void
    {
        $db = $this->db();

        if (!self::$usersTableInitialized) {
            $this->dropTableIfExists($db, 'uda_test_users');
            $db->exec('CREATE TABLE uda_test_users (id NUMBER PRIMARY KEY, name VARCHAR2(50))');
            self::$usersTableInitialized = true;
        } else {
            $db->exec('DELETE FROM uda_test_users');
        }

        $db->exec('INSERT INTO uda_test_users (id, name) VALUES (:id, :name)', ['id' => 1, 'name' => 'Alice']);
        $db->exec('INSERT INTO uda_test_users (id, name) VALUES (:id, :name)', ['id' => 2, 'name' => 'Bob']);
    }

    protected function resetEmployeesTable(): void
    {
        $db = $this->db();

        if (!self::$employeesTableInitialized) {
            $this->dropTableIfExists($db, 'uda_test_employees');
            $db->exec('CREATE TABLE uda_test_employees (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_no VARCHAR2(20) UNIQUE,
                first_name VARCHAR2(50),
                last_name VARCHAR2(50),
                salary NUMBER
            )');
            self::$employeesTableInitialized = true;
        } else {
            $db->exec('DELETE FROM uda_test_employees');
        }

        $db->exec(
            'INSERT INTO uda_test_employees (employee_no, first_name, last_name, salary)
            VALUES (:no, :first, :last, :salary)',
            ['no' => 'E001', 'first' => 'Alice', 'last' => 'One', 'salary' => 100000]
        );
        $db->exec(
            'INSERT INTO uda_test_employees (employee_no, first_name, last_name, salary)
            VALUES (:no, :first, :last, :salary)',
            ['no' => 'E002', 'first' => 'Bob', 'last' => 'Two', 'salary' => 120000]
        );
    }

    protected function normalizeRow(?array $row): array
    {
        if ($row === null) {
            return [];
        }

        $normalized = [];

        foreach ($row as $key => $value) {
            $normalized[strtolower((string) $key)] = $this->castValue($value);
        }

        return $normalized;
    }

    protected function resetNumbersTable(): void
    {
        $db = $this->db();

        if (!self::$numbersTableInitialized) {
            $this->dropTableIfExists($db, 'uda_test_numbers');
            $db->exec('CREATE TABLE uda_test_numbers (id NUMBER PRIMARY KEY, value NUMBER NOT NULL)');
            self::$numbersTableInitialized = true;
        } else {
            $db->exec('DELETE FROM uda_test_numbers');
        }

        for ($i = 1; $i <= 10; $i++) {
            $db->exec(
                'INSERT INTO uda_test_numbers (id, value) VALUES (:id, :value)',
                ['id' => $i, 'value' => $i * 10]
            );
        }
    }

    private function dropTableIfExists(Database $db, string $table): void
    {
        try {
            $db->exec('DROP TABLE ' . $table . ' PURGE');
        } catch (QueryException $e) {
            if (stripos($e->getMessage(), 'ORA-00942') === false) {
                throw $e;
            }
        }
    }

    private function castValue(mixed $value): mixed
    {
        if (is_string($value) && is_numeric($value)) {
            if (ctype_digit($value)) {
                return (int) $value;
            }

            return (float) $value;
        }

        return $value;
    }

    private static function initializeDatabase(): void
    {
        try {
            if (defined('UDA_ORACLE_TEST_CONFIG')) {
                self::$db = Database::connect(self::CONNECTION_NAME, UDA_ORACLE_TEST_CONFIG);

                return;
            }

            self::$ownedConfigPath = self::writeTempConfig(self::buildOracleConfig());
            self::$db = Database::connect(self::CONNECTION_NAME, self::$ownedConfigPath);
        } catch (ConfigException | QueryException | \PDOException $e) {
            self::$skipReason = 'Oracle connection unavailable: ' . $e->getMessage();
        } catch (\Throwable $e) {
            self::$skipReason = 'Oracle initialization failed: ' . $e->getMessage();
        }
    }

    /**
     * @return array<string,mixed>
     */
    private static function buildOracleConfig(): array
    {
        return [
            'defaults' => ['connection' => self::CONNECTION_NAME],
            'connections' => [
                self::CONNECTION_NAME => [
                    'driver' => 'oracle',
                    'params' => self::buildOracleParams(),
                    'user' => self::env('UDA_ORACLE_USER', 'uda_test'),
                    'pass' => self::env('UDA_ORACLE_PASSWORD', 'uda_test_pw'),
                ],
            ],
        ];
    }

    /**
     * @return array<string,mixed>
     */
    private static function buildOracleParams(): array
    {
        $dsn = self::env('UDA_ORACLE_DBNAME');

        if ($dsn !== null && $dsn !== '') {
            return ['dbname' => $dsn];
        }

        return [
            'host' => self::env('UDA_ORACLE_HOST', '127.0.0.1'),
            'port' => (int) self::env('UDA_ORACLE_PORT', '1521'),
            'service' => self::env('UDA_ORACLE_SERVICE', 'FREEPDB1'),
        ];
    }

    private static function env(string $var, ?string $default = null): ?string
    {
        $value = getenv($var);

        if ($value === false) {
            return $default;
        }

        $value = trim($value);

        return $value === '' ? $default : $value;
    }

    /**
     * @param array<string,mixed> $config
     */
    private static function writeTempConfig(array $config): string
    {
        $path = sys_get_temp_dir() . '/uda-oracle-' . bin2hex(random_bytes(4)) . '.json';
        file_put_contents($path, json_encode($config, JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR));

        return $path;
    }

    public function suppressIdentifierWarnings(int $severity, string $message): bool
    {
        if ($severity === E_WARNING
            && str_contains($message, 'Identifier.php')
            && str_contains($message, 'range out of order in character class')) {
            return true;
        }

        return false;
    }
}
