<?php

declare(strict_types=1);

namespace Tests\Oracle;

use PHPUnit\Framework\TestCase;
use UDA\Config;
use UDA\Database;
use UDA\Exception\ConfigException;
use UDA\Exception\QueryException;

abstract class OracleTestCase extends TestCase
{
    protected const CONNECTION_NAME = 'oracle_smoke';

    /** @var Database|null */
    private static ?Database $db = null;

    private static ?string $configPath = null;

    private static ?string $skipReason = null;

    private bool $errorHandlerActive = false;

    protected function setUp(): void
    {
        parent::setUp();

        set_error_handler([$this, 'suppressIdentifierWarnings'], E_WARNING);
        $this->errorHandlerActive = true;

        if (!extension_loaded('pdo_oci')) {
            $this->markTestSkipped('pdo_oci extension not loaded');
        }

        if (self::$db === null && self::$skipReason === null) {
            self::initializeDatabase();
        }

        if (self::$skipReason !== null) {
            $this->markTestSkipped(self::$skipReason);
        }
    }

    public static function tearDownAfterClass(): void
    {
        if (self::$configPath && file_exists(self::$configPath)) {
            unlink(self::$configPath);
            self::$configPath = null;
        }

        Config::clearForTests();
        self::$db = null;
        self::$skipReason = null;
    }

    protected function tearDown(): void
    {
        if ($this->errorHandlerActive) {
            restore_error_handler();
            $this->errorHandlerActive = false;
        }

        parent::tearDown();
    }

    protected function db(): Database
    {
        \assert(self::$db !== null, 'Oracle database connection must be initialized.');

        return self::$db;
    }

    protected function resetUsersTable(): void
    {
        $db = $this->db();

        try {
            $db->exec('DROP TABLE uda_test_users');
        } catch (QueryException $e) {
            // ORA-00942 (table not found) and similar should be ignored for cleanup
            if (stripos($e->getMessage(), 'ORA-00942') === false) {
                throw $e;
            }
        }

        $db->exec('CREATE TABLE uda_test_users (id NUMBER PRIMARY KEY, name VARCHAR2(50))');
        $db->exec('INSERT INTO uda_test_users (id, name) VALUES (:id, :name)', ['id' => 1, 'name' => 'Alice']);
        $db->exec('INSERT INTO uda_test_users (id, name) VALUES (:id, :name)', ['id' => 2, 'name' => 'Bob']);
        $db->exec('COMMIT');
    }

    protected function resetEmployeesTable(): void
    {
        $db = $this->db();

        try {
            $db->exec('DROP TABLE uda_test_employees');
        } catch (QueryException $e) {
            if (stripos($e->getMessage(), 'ORA-00942') === false) {
                throw $e;
            }
        }

        $db->exec('CREATE TABLE uda_test_employees (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_no VARCHAR2(20) UNIQUE,
            first_name VARCHAR2(50),
            last_name VARCHAR2(50),
            salary NUMBER
        )');

        $db->exec('INSERT INTO uda_test_employees (employee_no, first_name, last_name, salary)
            VALUES (:no, :first, :last, :salary)', ['no' => 'E001', 'first' => 'Alice', 'last' => 'One', 'salary' => 100000]);
        $db->exec('INSERT INTO uda_test_employees (employee_no, first_name, last_name, salary)
            VALUES (:no, :first, :last, :salary)', ['no' => 'E002', 'first' => 'Bob', 'last' => 'Two', 'salary' => 120000]);

        $db->exec('COMMIT');
    }

    protected function normalizeRow(?array $row): array
    {
        if ($row === null) {
            return [];
        }

        $normalized = [];

        foreach ($row as $key => $value) {
            $normalized[strtolower((string) $key)] = $this->castValue($value);
        }

        return $normalized;
    }

    private function castValue(mixed $value): mixed
    {
        if (is_string($value) && is_numeric($value)) {
            if (ctype_digit($value)) {
                return (int) $value;
            }

            return (float) $value;
        }

        return $value;
    }

    protected function resetNumbersTable(): void
    {
        $db = $this->db();

        try {
            $db->exec('DROP TABLE uda_test_numbers');
        } catch (QueryException $e) {
            if (stripos($e->getMessage(), 'ORA-00942') === false) {
                throw $e;
            }
        }

        $db->exec('CREATE TABLE uda_test_numbers (id NUMBER PRIMARY KEY, value NUMBER NOT NULL)');

        for ($i = 1; $i <= 10; $i++) {
            $db->exec(
                'INSERT INTO uda_test_numbers (id, value) VALUES (:id, :value)',
                ['id' => $i, 'value' => $i * 10]
            );
        }

        $db->exec('COMMIT');
    }

    private static function initializeDatabase(): void
    {
        Config::clearForTests();

        $config = self::buildOracleConfig();

        try {
            self::$configPath = self::writeTempConfig($config);
            self::$db = Database::connect(self::$configPath);
        } catch (ConfigException | QueryException | \PDOException $e) {
            self::$skipReason = 'Oracle connection unavailable: ' . $e->getMessage();
        } catch (\Throwable $e) {
            self::$skipReason = 'Oracle initialization failed: ' . $e->getMessage();
        }
    }

    /**
     * @return array<string,mixed>
     */
    private static function buildOracleConfig(): array
    {
        $config = [
            'defaults' => ['connection' => self::CONNECTION_NAME],
            'connections' => [
                self::CONNECTION_NAME => [
                    'driver' => 'oci',
                    'params' => self::buildOracleParams(),
                    'user' => self::env('UDA_ORACLE_USER', 'system'),
                    'pass' => self::env('UDA_ORACLE_PASSWORD', '@@@oracle@@@'),
                ],
            ],
        ];

        return $config;
    }

    /**
     * @return array<string,mixed>
     */
    private static function buildOracleParams(): array
    {
        $dsn = self::env('UDA_ORACLE_DBNAME');

        if ($dsn !== null && $dsn !== '') {
            return ['dbname' => $dsn];
        }

        return [
            'host' => self::env('UDA_ORACLE_HOST', '127.0.0.1'),
            'port' => (int) self::env('UDA_ORACLE_PORT', '1521'),
            'service' => self::env('UDA_ORACLE_SERVICE', 'FREEPDB1'),
        ];
    }

    private static function env(string $var, ?string $default = null): ?string
    {
        $value = getenv($var);

        if ($value === false) {
            return $default;
        }

        $value = trim($value);

        return $value === '' ? $default : $value;
    }

    /**
     * @param array<string,mixed> $config
     */
    private static function writeTempConfig(array $config): string
    {
        $path = sys_get_temp_dir() . '/uda-oracle-' . bin2hex(random_bytes(4)) . '.json';
        file_put_contents($path, json_encode($config, JSON_PRETTY_PRINT));

        return $path;
    }

    public function suppressIdentifierWarnings(int $severity, string $message): bool
    {
        if ($severity === E_WARNING
            && str_contains($message, 'Identifier.php')
            && str_contains($message, 'range out of order in character class')) {
            return true;
        }

        return false;
    }
}
